### ISSUE TITLE
Lazy Button

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#10]
## Value Proposition

**As a user**
**I want to have a button, to skip the current workout**
**so that I can be lazy**
​

## Description

​

## Acceptance Criteria

- [ ] there is a button that reads: "Skip"
- [ ] e.g. all inputs are required, show warning if empty.
- [ ] ...
      ​

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
      ​

## Complexity

... (T-Shirt Sizes XS to XL)
