### ISSUE TITLE
Refactoring Calendar

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#12]
## Value Proposition

**As a programmer**
**I want to be able to understan the code**
**so that I can change the code and fix bugs.** 
​

## Description
​

## Acceptance Criteria

- [ ] Logic high up
- [ ] Components have their own files
- [ ] States as high up as necessary.
- [ ] readable code.
- [ ] good names for variables, components etc.
- [ ] reuse components.
- [ ] good folder structure
      ​

## Tasks

- [ ] look: which is the mian file where the logic needs to be.
- [ ] use folders and subfolders for components.
- [ ] add comments if necessary, but not too many.
- [ ] look: which names changed in the progress and which names could be better.
- [ ] div-Components: look: Which one do I need which one are double.
- [ ] ask: are the states in their correct files?
      ​

## Complexity

S
