### ISSUE TITLE
Testing Calendar

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#13]
## Value Proposition

**As a programmer** 
**I want to be able to test the calendar**
**so that in the future I find bugs more easily.**
​

## Description

​Testing

## Acceptance Criteria

- [ ] Test if there are Input fields with label: Kilograms, etc.
- [ ] if you click on the image, then you have different input fields.
- [ ] Test if there is a calendar with different divs that can be clicked and a different date is displayed.
- [ ] Test if you create a new entry that you can display it (with the info) and delete it.
      ​

## Tasks

- [ ] write the tests best in the component folders themselves. only use the main app file when necessary.
- [ ] use jest
      ​

## Complexity

... M
