### ISSUE TITLE
Calendar Database

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#14]
## Value Proposition

**As a user**
**I want to save my data and access it from everywhere**
**so that I can travel and use multiple devices**
​

## Description

Database connection. first no login just one calendar for all users.
​

## Acceptance Criteria

- [ ] Write the data to the database
- [ ] get the data from the database
- [ ] change the data from the database
- [ ] delete the data from the database
      ​

## Tasks

- [ ] use mongoDB atlas
- [ ] think: on which page does it make most sense to use fetch?
- [ ] dont think about security yet.
- [ ] create a user with a password that has limited rights. dont use the admin account.
      ​

## Complexity

... M
