### ISSUE TITLE
Graph of Excercises

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#19]
## Value Proposition

**As a user**
**I want to see my results in a graph**
**so that I can see my progress** 
​

## Description

​Shows a graph that displays the run kilometers and other data over time over a period

## Acceptance Criteria

- [ ] A graph is shown
- [ ] the graph shows kilometers over time.
      ​

## Tasks

- [ ] i will make a component that can show any data over time. the data is given to it by the parent.
- [ ] I might write it on my own or use a package for the graph implementation.
- [ ] thus I will first create a line with the dates.
- [ ] then I will input the graph of kilometers over time.
- [ ] question: do I want the component to calculate the date correctly or do I give the component the calculated data?

      ​

## Complexity

... M
