### ISSUE TITLE
Favorite Exercise

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#20]
## Value Proposition

**As a user**
**I want to favorite an exercise** 
**so that I can look it up anytime**
​

## Description

Favorite Star on top right of exercise card. Favorite Exercises Site integrated on the strength.js page.
​

## Acceptance Criteria

- [ ] There is a star in the top right of the exercise card.
- [ ] you can toggle the star
- [ ] if you activate the star you can see it on the favorite page.
      ​

## Tasks

- [ ] get an svg star that has two states one off and one on.
- [ ] put it in the top right corner.
- [ ] if the card is favorites, the info get posted on the database, so they wont get lost.
- [ ] create a favorite site that only shows the favorited cards. it fetches the cards from the database and not the exercise api.
- [ ] Possible problem: if I star a exercise from the api it doesnt have a _id yet so I dont know which one it is. figure that one out.
      ​

## Complexity

... M
