### ISSUE TITLE
Make Responsive

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#32]
## Value Proposition

**As a user** 
**I want the app to be responsive**
**so that I can use the app in my mobile phone and in the browser**
​

## Description

App was written for mobile.
Make it responsive.
​

## Acceptance Criteria

- [ ] Different view for mobile and 1080p desktop.
- [ ] the calendar should be bigger on bigger screens.
- [ ] not too much empty space on 1080p.
      ​

## Tasks

- [ ] Question: Which phones and resolutions do I want to support?
- [ ] Write the necessary media queries.
      ​

## Complexity

S

**Comment by Long-HaHoang** [comment]
Hi Lenz,
You don't need this story.
Your styling should be responsive from the beginning.
The goal nowadays is mobile-first.
Of course, it's not mobile-only, and you clearly put some thought into it.
But this story doesn't bring more value. 
You should combine this with an other styling story.

**Comment by lenzloesche** [comment]
> Hi Lenz, You don't need this story. Your styling should be responsive from the beginning. The goal nowadays is mobile-first. Of course, it's not mobile-only, and you clearly put some thought into it. But this story doesn't bring more value. You should combine this with an other styling story.

thank you for your comment.
