### ISSUE TITLE
FavoriteExercise integration

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#33]
## Value Proposition

**As a user** 
**I want to be able to select my favorite exercises**
**so that I can use them in the calendar** 
​

## Description
​
![image](https://user-images.githubusercontent.com/117287151/227705882-f15f47f4-b44d-4212-9998-268456a8fc17.png)
A dropdown menu for selecting the favorite exercise I want.

## Acceptance Criteria

- [ ] dropdown menu with the favorite exercises on the calendar.js page
- [ ] but still an input field if I want to change something.
      ​

## Tasks

- [ ] make favorite exercises available in the _app.js
- [ ] make a dropdown menu with favorited exercises.
      ​

## Complexity

S

**Comment by reyk-zepper** [comment]
looks good!....happy coding🙏🏻
