### ISSUE TITLE
Diet Detail Page

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#42]
## Value Proposition

**As a user** 
**I want to see the details of the selected food** 
**so that I know all the nutrition from it.**
​

## Description

![image](https://user-images.githubusercontent.com/117287151/229075925-57627309-e837-4932-a2ad-5c173e4c2f86.png)

## Acceptance Criteria

- [ ] The name of the food is displayed
- [ ] the additional data is displayed with bars.
- [ ] there is a back button.
- [ ] there is a detail page button selected.
      ​

## Tasks

- [ ] dynamically create a page? I am not sure yet about which is the best way to do it. Or i just have it on the same page and just have a detailDisplayed=true function with detailName="current food"
- [ ] use the data already fetched from the api.
- [ ] use the jsx styling already done on the search page.
- [ ] make button for detail page.
      ​

## Complexity

M

**Comment by reyk-zepper** [comment]
detailed and good to understand...thank you sir!
