### ISSUE TITLE
Questionaire

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#6]
## Value Proposition

**As a user** 
**I want to inout my data**
**so that the app can work properly with a plan for the training**
​

## Description

![image](https://user-images.githubusercontent.com/117287151/225346117-9317832a-16af-4348-8605-4cc31139d983.png)
​

## Acceptance Criteria

- [ ] input of weight
- [ ] input of gender
- [ ] input of age
- [ ] input of what they want to change most
- [ ] input of how much they want to invest.
      ​

## Tasks

- [ ] create a form
- [ ] input of weight
- [ ] input of gender
- [ ] input of age
- [ ] input of what they want to change most
- [ ] input of how much they want to invest.
      ​

## Complexity

... S
