### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#8]
## Value Proposition

**As a user** 
**I want to switch between pages** 
**so that I can see each page** 
​

## Description

![Image](https://user-images.githubusercontent.com/117287151/226607220-41951fb4-f232-45f3-a2fa-ad1b7281af73.png)

## Acceptance Criteria

- [ ] Bottom of screen is a Navigation Bar
- [ ] It has links: calendar, strength
- [ ] the current selected site-link has a different color
      ​

## Tasks

- [ ] use the app.js for the navigation
- [ ] add links to the pages:  calendar, strength
- [ ] use components that I already have.
      ​

## Complexity

... S
