### ISSUE TITLE
Training Plan

### ISSUE THREAD

**Issue by lenzloesche** [lenzloesche/capstone-project#9]
## Value Proposition

**As a user** ... (User, Author, logged in User...)  
**I want to see my training plan** ... (describe the goal)  
**so that I know what to work out next** ... (describe the reason)  
​

## Description

logic calculation.
​

## Acceptance Criteria

- [ ] calculates how many days of the week to work out
- [ ] calculates the free days
- [ ] calculates a goal
- [ ] 
      ​

## Tasks

- [ ] get the input from the form
- [ ] calculates the free days
- [ ] calculates a goal
- [ ] 
      ​

## Complexity

... (T-Shirt Sizes XS to XL)
